version: '3.7'

services:
  hadoop:
    container_name: hadoop
    build: ./hadoop
    ports:
      - "8088:8088"  # Web UI für YARN
      - "9870:9870"  # HDFS Web UI
      - "9864:9864"  # HDFS Web UI
      - "10000:10000"  # HiveServer2
      - "8032:8032"  # Resource Manager
      - "8030:8030"
      - "8031:8031"
      - "9000:9000"  # HDFS Namenode
      - "8888:8888"  # Jupyter
    networks:
      - bigdatanet

  airflow:
    container_name: airflow
    build: ./airflow
    ports:
      - "8080:8080"  # Web UI für Airflow
    environment:
      - load_examples=n
      - executor_type=LocalExecutor
    volumes:
     - type: bind
       source: ./airflow/dags
       target: /home/airflow/airflow/dags/
     - type: bind
       source: ./airflow/python
       target: /home/airflow/airflow/python/
    networks:
      - bigdatanet

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes: 
      - mongo:/data/mongodb
      - ./init.js:/docker-entrypoint-initdb.d/init.js
    environment:
      mongo_root_user: rootuser
      mongo_root_password: rootpassword
      mongo_database: mtg_database
    networks:
      - bigdatanet

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      mongo_server: mongo
      mongo_port: 27017
      mongo_enable_admin: 'false'
      mongo_auth_database: mtg_database
      mongo_auth_username: rootuser
      mongo_auth_password: rootpassword
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    networks:
      - bigdatanet

  backend:
    container_name: backend
    build: ./Backend
    command: sh -c "npm run build && npm start"
    image: my-backend:latest
    ports:
      - "5201:5201" 
    networks:
      - bigdatanet
    environment:
      mongo_username: rootuser
      mongo_password: rootpassword
      mongo_database: mtg_database
      mongo_hostname: mongo
      mongo_port: 27017

  frontend:
    container_name: frontend
    build: ./Frontend
    command: ng serve --host
    ports:
      - "4200:4200"
    networks:
      - bigdatanet

volumes:
  mongo:

networks:
  bigdatanet:
    driver: bridge
