version: '3.7'

services:
  hadoop:
    container_name: hadoop
    build: ./hadoop
    ports:
      - "8088:8088"  # Web UI für YARN
      - "9870:9870"  # HDFS Web UI
      - "9864:9864"  # HDFS Web UI
      - "10000:10000"  # HiveServer2
      - "8032:8032"  # Resource Manager
      - "8030:8030"
      - "8031:8031"
      - "9000:9000"  # HDFS Namenode
      - "8888:8888"  # Jupyter
    networks:
      - bigdatanet

  airflow:
    container_name: airflow
    build: ./airflow
    ports:
      - "8080:8080"  # Web UI für Airflow
    environment:
      - LOAD_EX=n
      - EXECUTOR=LocalExecutor
    volumes:
     - type: bind
       source: ./airflow/dags
       target: /home/airflow/airflow/dags/
     - type: bind
       source: ./airflow/python
       target: /home/airflow/airflow/python/
    networks:
      - bigdatanet

  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Root-Passwort für MySQL
      MYSQL_DATABASE: mtg_database         # Standarddatenbank
      MYSQL_USER: user                   # Benutzername
      MYSQL_PASSWORD: userpassword       # Benutzer-Passwort
    ports:
      - "3307:3307"  # Standard MySQL-Port
    networks:
      - bigdatanet


  backend:
    container_name: backend
    build: ./Backend
    command: sh -c "npm run build && npm start"
    image: my-backend:latest
    ports:
      - "5201:5201" 
    networks:
      - bigdatanet
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=userpassword
      - DB_NAME=mtg_database


  frontend:
    container_name: frontend
    build: ./Frontend
    command: ng serve --host
    ports:
      - "4200:4200"
    networks:
      bigdatanet:

volumes:
        mysql:

networks:
  bigdatanet:
    driver: bridge
