version: '3.7'

services:
  hadoop:
    container_name: hadoop
    build: ./hadoop
    ports:
      - "8088:8088"  # Web UI für YARN
      - "9870:9870"  # HDFS Web UI
      - "9864:9864"  # HDFS Web UI
      - "10000:10000"  # HiveServer2
      - "8032:8032"  # Resource Manager
      - "8030:8030"
      - "8031:8031"
      - "9000:9000"  # HDFS Namenode
      - "8888:8888"  # Jupyter
    networks:
      - bigdatanet

  airflow:
    container_name: airflow
    build: ./airflow
    ports:
      - "8080:8080"  # Web UI für Airflow
    environment:
      - load_examples=n
      - executor_type=LocalExecutor
    volumes:
     - ./airflow/dags:/home/airflow/airflow/dags
     - ./airflow/python:/home/airflow/airflow/python
    networks:
      - bigdatanet

  postgresql:
    container_name: postgresql
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgresql
    ports:
      - "5432:5432"
    networks:
      bigdatanet:

  backend:
    container_name: backend
    build: ./Backend
    command: sh -c "npm run build && npm start"
    image: my-backend:latest
    ports:
      - "5201:5201" 
    networks:
      - bigdatanet
    environment:
      POSTGRES_HOST: postgresql
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    depends_on:
      - postgresql

frontend:
  container_name: frontend
  build: ./Frontend
  ports:
    - "8080:80"
  networks:
    - bigdatanet

volumes:
  mongo:

networks:
  bigdatanet:
    driver: bridge
